version: '3.7'

services:
  flask_api:
    container_name: flask_api
    build:
      context: ./flask_api/
      dockerfile: Dockerfile.prod
    expose:
      - 5000
  react_app:
    container_name: react_app
    build:
      context: ./react_app/
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'